### PR TITLE
Added LowerDirichlet legendre basis

### PR DESCRIPTION
**Pull request by thoeschler**
Hi,
I added a LowerDirichet basis for Legendre polynomials including inhomogeneous boundary conditions.

### CODE REVIEW

**Comment by mikaem** [comment]
This looks great. Do you have any idea why the tests are failing? I don't see why this PR should make the mixed boundary conditions demo fail?

**Comment by thoeschler** [comment]
Not really. I tested the basis for both homogeneous and inhomogeneous boundary conditions and it worked fine on my machine.

**Comment by mikaem** [comment]
Looks you're not merged in with the latest master. The error is due to [this line](https://github.com/thoeschler/shenfun/blob/c787b8eaae321909392e2456276574be287f567f/shenfun/legendre/bases.py#L520), which should include `mean=None`, not `mean=0`. This was changed very recently.

**Comment by thoeschler** [comment]
I just updated the PR. All checks have passed now.

**Pull request merged**
