### PR TITLE
Added DirichletNeumannDirichlet basis for legendre polynomials

### PR DESCRIPTION
**Pull request by thoeschler**
Hi,
I would like to add another basis with legendre polynomials. If you can think of a better name for the basis please let me know 😄.

### CODE REVIEW

**Comment by mikaem** [comment]
What is the intended use for this space?

**Comment by thoeschler** [comment]
I need this space for an application in gradient elasticity.

**Comment by mikaem** [comment]
Ok. Don't you need the other way around as well? With two bc's on the left and one on the right? I think that is the most common approach for third order equations. Petrov-Galerkin with different (symmetric) test and trial spaces.

**Comment by mikaem** [comment]
Perhaps you should also have a look at[ inhomogeneous boundary conditions in 2D?](https://github.com/spectralDNS/shenfun/blob/e504fb6b9efbbd6620a42119d75e264753e009e1/shenfun/tensorproductspace.py#L1715) They will not work for anything higher than second order at the moment. I haven't looked further.

**Comment by thoeschler** [comment]
> 
> 
> Ok. Don't you need the other way around as well? With two bc's on the left and one on the right? I think that is the most common approach for third order equations. Petrov-Galerkin with different (symmetric) test and trial spaces.

Actually the equations are of fourth order even though the basis only has three conditions.  So I was thinking that the usual Galerkin approach would be adequate here.

**Pull request merged**
